### ISSUE TITLE
elmacro stops working after a C-g, elmacro mode has to be toggled off and on to reset

### ISSUE THREAD

**Issue by jeffbski** [Silex/elmacro#13]
First, thanks for an awesome library. I love it.

For some reason elmacro stops working after an C-g and only starts working again after toggling the mode off and on with (elmacro-mode)  (elmacro-mode)

I understand that macro recording stops after C-g, however it can be resumed with C-u C-u C-x ( and one can even go in and edit the macro taking whatever caused the problem using C-x C-k C-e and have a working macro.

However is seems that elmacro is lost after the C-g, it doesn't seem to be able to use any macro recordings after that until it is reset by toggling the mode off and on.

It would be great if there would be some way to prevent C-g from causing such havoc on elmacro.

I'm certainly willing to edit the macro as needed (either in emacs macro editor, or via the list that elmacro generates) if I happen to cause a C-g as long as elmacro can continue to work and not get lost.

Thanks for any advice or help

**Comment by Silex** [comment]
Hi,

Thanks for the report, it is indeed weird that elmacro gets lost by a `C-g` because the way it works it's not supposed to. Theorically what'd happen is more that `C-g` being reported as part of the macro (which would be another bug).

I'll investiguate and keep you updated.

**Comment by jeffbski** [comment]
Thanks! You can certainly wait to deal with this in the new refactor and maybe it isn't even an issue in the new version.

I just have to do my best to not use C-g when I am recording :-) (not an easy habit to break since it is second nature for me)

 I really like the library. It is going to be great for me. You just extended the love I have for Emacs, the power of having a full programming environment available during runtime. Awesome!

 I am going to use this to help with creating training. I can record editing files to add features to programs and then generate the elisp. With the elisp I can insert some pause-edit at points where I want to stop to talk about the code that was added. I created a function called `pause-edit` which saves the current point and mark, outputs a message to remind me where I am in my lesson, then calls recursive-edit allowing me interactive control to cursor around and explain the code before invoking the resume with C-M-c. 

It seems like it is going to be really nice. I love being able to pause execution and being able to cursor around before continuing. I also love having the full power of elisp at my hands to do anything I need.

Here is my implementation for the `pause-edit` function I am using with elmacro recorded macros.

```lisp
;; function great for using with elmacro recording since it
;;  - saves point and mark
;;  - outputs a message
;;  - starts recursive-edit allowing free cursor until C-M-c resumes
(defun pause-edit (msg)
  "save-excurstion ouptut message recursive-edit - C-M-c to resume"
  (save-excursion
    (message msg)
    (recursive-edit)))
```

**Comment by Silex** [comment]
@jeffbski: hum, there are several things goingo on:

> I understand that macro recording stops after C-g, however it can be resumed with C-u C-u C-x ( and one can even go in and edit the macro taking whatever caused the problem using C-x C-k C-e and have a working macro.

Resuming/editing macros will never work with elmacro. Elmacro just records whatever happens while it happens, and then it extracts whatever is between `kmacro-start-macro` and `kmacro-end-macro` (and all their equivalent). See https://github.com/Silex/elmacro/blob/master/elmacro.el#L108 for more details.

 > However is seems that elmacro is lost after the C-g, it doesn't seem to be able to use any macro recordings after that until it is reset by toggling the mode off and on.

That I just couldn't reproduce... for example <kbd>M-x elmacro-show-last-commands</kbd> always worked no matter how hard I pressed C-g. Recording new macros also always worked. Can you show me a step-by-step way to reproduce?

**Comment by jeffbski** [comment]
@Silex Thanks for the update on how elmacro works. That makes sense on why resuming a macro doesn't work, however I see that I can use elmacro-show-last-commands to get more history.

I'm having trouble reproducing the issue now too.

I'll go ahead and close the issue for now. If it starts acting up again and I can reproduce it we can reopen.

Thanks for looking into it. 

I am loving using this library.

**Comment by Silex** [comment]
In my refactor I attempt to store everything as a raw list of commands (atm I manipulate some of it while storing), and then this allows to implement everything as togglable "filters", so theorically it'd be possible to write a "resume macro" filter... e.g ones that skips from the last `keyboard-quit` to the next `kmacro-start-macro`...

**Comment by jeffbski** [comment]
That sounds fantastic. 

It also might be nice to have a way to map certain commands into other commands automatically. I'm not sure what the interface would look like, but that would be powerful.

**Comment by Silex** [comment]
@jeffbski: the big refactor happened! You can now define your own processors. Check the README.

**Comment by jeffbski** [comment]
I will, thanks for the heads up!
