### ISSUE TITLE
"You have to record a macro before using this command (F3/F4)."

### ISSUE THREAD

**Issue by dll128** [Silex/elmacro#14]
Hi there.

I was really excited when I found elmacro! Unfortunately, I'm having problems with it. I've tried the example usage I saw on [emacs.stackexchange](http://emacs.stackexchange.com/questions/70/how-to-save-a-keyboard-macro-as-a-lisp-function):

    F3 C-e M-b M-u C-a C-n F4

and then:

    M-x elmacro-show-last-macro upcase-last-word

and got the error message:

    You have to record a macro before using this command (F3/F4).

Please help! :'(

**Comment by Silex** [comment]
Hello! Can you tell me a bit more about your config? What emacs version? How did you install elmacro? Does `M-x elmacro-show-last-commands` works?

In the meantime, try turning elmacro mode off and on again to see if that fixes it, or try with `C-x (` and C-x )` to record the macro.

**Comment by Silex** [comment]
@dll128: I suspect you simply forgot to turn elmacro-mode on. Use `M-x elmacro-mode`

**Comment by Silex** [comment]
Fixed in d4a54dc

Feel free to reopen if it still happens.

**Comment by dll128** [comment]
Wow, do I feel stupid. You were right; I didn't activate elmacro-mode. Thank you for the help!

**Comment by Silex** [comment]
No worries :smile:
