### ISSUE TITLE
Interoperability with org-mode, outshine, etc

### ISSUE THREAD

**Issue by theldoria** [Silex/elmacro#17]
When I perform the following macro recording in org-mode:

```elisp
(fset 'glossarer
   [down home ?- ?  S-end ?< ?< ?< ?  ?: ?: delete ? ])
```

I get from `elmacro-show-last-macro` this:

```elisp
(defun last-macro ()
  (interactive)
  (next-line 1 1)
  (beginning-of-visual-line 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (end-of-visual-line 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (org-self-insert-command 1)
  (delete-forward-char 1 nil))
```

Which is not that useful.

The example macro is used to transform a line like this:

```
cursor-position
ABC
Meaning of ABC
```

to this:

```org
- <<<ABC>>> :: Meaning of ABC
```

Note: I use `smartparens.el` to insert `<>` parens using this config:

```elisp
(sp-with-modes 'org-mode
  (sp-local-pair "<<" ">>" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC"))))
```

**Comment by Silex** [comment]
Ah, `org-self-insert-command`, interesting... 

Can you give https://github.com/Silex/elmacro/blob/org-mode-support/elmacro.el a try and report if it works? (the new macro should have `last-command-event` set for each `org-self-insert-command`).

**Comment by theldoria** [comment]
It works for org-mode now, however `smartparens` is not triggered and I end up with

```org
- ABC<<< :: Foo bar
```

Shall I file that as a seperated issue?

**Comment by Silex** [comment]
Ah, found this: https://github.com/Fuco1/smartparens/blob/master/smartparens.el#L1577

Sounds like smartparens had to tackle the same kind of problems I do... let me try to figure out if what is reasonably feasible or not.

I feels like we are about to open a can of worms tho :stuck_out_tongue_closed_eyes:

**Comment by et2010** [comment]
It works like a charm, with the fix it even works with orgmode and smartparens, tested on orgmode 9.0, emacs 25.1 and latest melpa packages.

Thanks for this great app! Now I can do some real customization:smile:

**Comment by Silex** [comment]
Note to self: also happens with `outshine`.

@Fuco1: I summon you here because of `sp--self-insert-commands` and `sp--special-self-insert-commands`.

I kinda suffer the same problem: having to have a list of these and treat them as a corner case. This sucks. I wondered if you had an idea on how would be the right way to tackle these, and if there are no other ways than doing it as we do now (https://github.com/Silex/elmacro/blob/org-mode-support/elmacro.el#L185), maybe extract this support as some common library between our packages.

**Comment by TLINDEN** [comment]
Hi,

I modified the function `elmacro-record-command` a little bit:

```emacs-lisp
(defun elmacro-record-command (advised-function function &optional record keys)
  "Advice for `call-interactively' which makes it temporarily record
commands in variable `command-history'."
  (let ((original-record record)
        retval)
    (elmacro-debug-message "[%s] ----- START -----" function)
    (setq record (or original-record (not (minibufferp)))) ;; don't record when in minibuffer
    (elmacro-debug-message "[%s] before - history %s record %s original %s"
                           function (car command-history) record original-record)
    (setq retval (funcall advised-function function record keys))
    (elmacro-debug-message "[%s] after - history %s" function (car command-history))
    (let* ((sexp (car command-history))
           (cmd (car sexp))
           (sic-mapped (command-remapping 'self-insert-command)))
      (when record
        (elmacro-debug-message "[%s] recording %s" function cmd)
          (unless (eq nil sic-mapped)
            (!cons (elmacro-setq-last-command-event) elmacro-command-history))
        (!cons sexp elmacro-command-history)
        (!cdr command-history)
        (elmacro-debug-message "[%s] clean %s" function (car command-history)))
      (elmacro-debug-message "[%s] ----- STOP -----" function)
      retval)))
```
It now checks if  `'self-insert-command` has been remapped with `'command-remapping`, which returns nil if no remapping is active.

Works for me in outshine and org mode.

**Comment by Silex** [comment]
@TLINDEN: ah nice, that might be sufficient and should cover all cases! I'll play with it

Thanks a lot

**Comment by Silex** [comment]
Ok guys, can you test https://github.com/Silex/elmacro/blob/self-insert-command/elmacro.el ?

I need to clean up "unwanted" `last-command-event` but overall it seems to fix the problem nicely.

**Comment by TLINDEN** [comment]
Works like a charm :+1:

**Comment by Silex** [comment]
Alright, waiting on @theldoria and @et2010 a bit and then I'll merge.

**Comment by Fuco1** [comment]
Hmm, I couldn't even get outshine to work, it defines some global keys right when you load the file, which conflicts with my setup :( I had to hack on the source a bit (why is there like 2000 commented lines?)

The solution with `command-remapping` is sweet, I didn't know about that, but that still wouldn't catch the `sp--special-self-insert-commands` list of offenders.  That however shouldn't be a problem here as you, I suppose, just translate that back to the command which was invoked.

@Silex btw it seems you deleted the branch? The links here don't work for me anymore.

**Comment by Silex** [comment]
The original patch was deleted yes but in my (last-1) message I linked to https://github.com/Silex/elmacro/blob/self-insert-command/elmacro.el which works.

**Comment by Silex** [comment]
Ok I pushed to master, please reopen this issue if needed.
