### ISSUE TITLE
Doesn't record inserts correctly with outshine enabled

### ISSUE THREAD

**Issue by TLINDEN** [Silex/elmacro#18]
In a buffer with emacs-lisp-mode and outshine-minor-mode, inserts are not correctly recorded, I get this when entering "hallo":
```
(defun last-macro ()
  (interactive)
  (outshine-self-insert-command 1)
  (outshine-self-insert-command 1)
  (outshine-self-insert-command 1)
  (outshine-self-insert-command 1)
  (outshine-self-insert-command 1))
```
If I disable outline, everyting works as expected.

Here's the relevant config which I use to enable outshine:
```
(require 'outshine)
(add-hook 'outline-minor-mode-hook 'outshine-hook-function)
(add-hook 'emacs-lisp-mode-hook 'outline-minor-mode)
```

best,
Tom

*UPDATE*: same thing in org-mode, it records inserts as `(org-self-insert-command 1)`.

**Comment by Silex** [comment]
Thanks, this a known issue and will be fixed by #17. Please continue discussion there :wink:
