### ISSUE TITLE
Is it tested with v25.1? 

### ISSUE THREAD

**Issue by mattiasw2** [Silex/elmacro#19]
elmacro-show-last-commands works, but elmacro-show-last-macro do not find the working macro.

**Comment by Silex** [comment]
Well, it works on emacs 25.1.1 here... How do you define your macro? I usually use F3/F4 but the other ways should work too.

**Comment by Silex** [comment]
@mattiasw2: ping

**Comment by mattiasw2** [comment]
Works as expected when I now retested.
