### ISSUE TITLE
How to filter `file-notify-handle-event` calls

### ISSUE THREAD

**Issue by CyborgMaster** [Silex/elmacro#28]
In trying to record a macro I'm getting a bunch of `file-notify-handle-event` calls:

```elisp
(defun last-macro ()
  (interactive)
  (move-end-of-line 1)
  (insert "fjdskl")
  (file-notify-handle-event
   `(file-notify
     (307
      (create)
      ".#observations.proto")
     file-notify-callback))
  (file-notify-handle-event
   `(file-notify
     (307
      (write)
      ".#observations.proto")
     file-notify-callback))
  (file-notify-handle-event
   `(file-notify
     (306
      (create)
      ".#observations.proto")
     file-notify-callback))
```

I assumed this would be easy to filter out using `elmacro-unwanted-commands-regexps`, so I set it equal to `("^(ido.*)$" "^(smex)$" "^(file-notify.*)$")`, but that doesn't work.  I'm sure there is something simple I am missing.  

Any hints on the right direction I should taking?

**Comment by CyborgMaster** [comment]
I think I may have solved it.   I've got the variable set to `("^(ido.*)$" "^(smex)$" "file-notify-handle-event)`, which seems to work.  However, now my question becomes how to interpret the original regexes in the variable: `"^(ido.*)$"` and  `"^(smex)$"`.  Why the parenthesis and the start and end anchors, using those seemed to break the functionality when wanted to add my own.

**Comment by Silex** [comment]
The regex is to match the whole text representation of the command. That's why we want to filter "(smex)" out, which regexp is `"^(smex)$"`. Remember Emacs's regexp are not PCRE :wink: 

Anyway I pushed a commit that filters `file-notify-*`

**Comment by Silex** [comment]
Ah but that's what you had. I guess you forgot to set the variable while testing?

Please report if what I tried works.

**Comment by CyborgMaster** [comment]
I'll give it a try on Monday when I'm back in the office.  The thing that was surprising to me was that `^(file-notify.*)$` didn't work, but `file-notify.*` did.  I assumed the regex was to match the whole command which is why I thought that the version with the anchors was the correct approach, but it didn't work and I'm not sure why.  I went back and forth multiple times applying each time to check and the results were consistent.
